name: summon_character
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  js_interop: ^0.0.1
  web: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

scripts:
  build: dart compile js lib/content_script.dart -o build/content_script.js && dart compile js lib/background.dart -o build/background.js